"""Initial migration

Revision ID: c5f565fd9cee
Revises: 
Create Date: 2025-03-22 05:08:22.406792

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import types


# revision identifiers, used by Alembic.
revision = 'c5f565fd9cee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_adresse',
    sa.Column('ad_code', sa.String(length=254), nullable=False, comment="Code unique de l'adresse"),
    sa.Column('ad_raclong', sa.String(length=1), nullable=True, comment="Défini si l'entité est raccordable en longueur (0/1)"),
    sa.Column('ad_datmodi', sa.DateTime(), nullable=True, comment="Date de dernière mise à jour de l'adresse"),
    sa.Column('ad_nomvoie', sa.String(length=254), nullable=True, comment='Nom de la voie'),
    sa.Column('ad_numero', sa.Integer(), nullable=True, comment="Numéro éventuel de l'adresse dans la voie"),
    sa.Column('ad_rep', sa.String(length=20), nullable=True, comment='Indice de répétition associé au numéro (Bis, A, 1...)'),
    sa.Column('ad_insee', sa.String(length=6), nullable=True, comment='Identifiant INSEE de la commune'),
    sa.Column('ad_postal', sa.String(length=20), nullable=True, comment='Code postal du bureau de distribution de la voie'),
    sa.Column('ad_commune', sa.String(length=254), nullable=True, comment='Nom officiel de la commune'),
    sa.Column('ad_hexacle', sa.String(length=254), nullable=True, comment='Code HEXACLE'),
    sa.Column('ad_distinf', sa.NUMERIC(precision=6, scale=2), nullable=True, comment='Distance en mètres de raccordement'),
    sa.Column('ad_isole', sa.String(length=1), nullable=True, comment='Pour distinguer les locaux isolés (1) ou non (0)'),
    sa.Column('ad_prio', sa.String(length=1), nullable=True, comment='Le raccordement est-il prioritaire (1) ou non (0)'),
    sa.Column('ad_racc', sa.String(length=2), nullable=True, comment='Type de raccordement du site'),
    sa.Column('ad_batcode', sa.String(length=100), nullable=True, comment='Identifiant du bâtiment dans une base externe'),
    sa.Column('ad_codtemp', sa.String(length=254), nullable=True, comment="Code temporaire avant création de l'ad_batcode"),
    sa.Column('ad_nombat', sa.String(length=254), nullable=True, comment="Nom du batiment tel que décrit par l'opérateur"),
    sa.Column('ad_ietat', sa.String(length=2), nullable=True, comment='Avancement du déploiement'),
    sa.Column('ad_imneuf', sa.String(length=1), nullable=True, comment="S'il s'agit d'un habitat en cours de construction (1) ou non (0)"),
    sa.Column('ad_gest', sa.String(length=254), nullable=True, comment="Gestionnaire d'immeuble"),
    sa.Column('ad_idatsgn', sa.DateTime(), nullable=True, comment='Date de signature de la convention avec le gestionnaire'),
    sa.Column('ad_iaccgst', sa.String(length=1), nullable=True, comment='Accord gestionnaire nécessaire (1) ou non (0)'),
    sa.Column('ad_nblres', sa.Integer(), nullable=True, comment='Nombre de locaux résidentiels'),
    sa.Column('ad_nblpro', sa.Integer(), nullable=True, comment='Nombre de locaux professionnels'),
    sa.Column('ad_nblent', sa.Integer(), nullable=True, comment="Nombre de locaux d'entreprises éligibles à une offre spécifique"),
    sa.Column('ad_nblpub', sa.Integer(), nullable=True, comment='Nombre de locaux exploités par des services publics'),
    sa.Column('ad_nblobj', sa.Integer(), nullable=True, comment='Nombre de locaux de type objet connectés'),
    sa.Column('ad_nblope', sa.Integer(), nullable=True, comment='Nombre de locaux exploités par des opérateurs télécoms'),
    sa.Column('ad_nbfotte', sa.Integer(), nullable=True, comment='Nombre de fibres FTTE'),
    sa.Column('ad_nbfogfu', sa.Integer(), nullable=True, comment='Nombre de fibres GFU'),
    sa.Column('ad_nbfotto', sa.Integer(), nullable=True, comment='Nombre de fibres FTTO'),
    sa.Column('ad_nbfotth', sa.Integer(), nullable=True, comment='Nombre de fibres FTTH'),
    sa.Column('ad_nbfofon', sa.Integer(), nullable=True, comment='Nombre de fibres noires'),
    sa.Column('ad_dta', sa.String(length=1), nullable=True, comment='1 si Diagnostic Technique Amiante obligatoire, 0 sinon'),
    sa.Column('geom', types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True, comment='Point abstrait (géométrie)'),
    sa.Column('ad_ban_id', sa.String(length=24), nullable=True, comment='Identifiant Base Adresse Nationale'),
    sa.Column('ad_fantoir', sa.String(length=10), nullable=True, comment='Identifiant FANTOIR'),
    sa.Column('ad_alias', sa.String(length=254), nullable=True, comment='Nom en langue régionale ou autre appellation différente'),
    sa.Column('ad_nom_ld', sa.String(length=254), nullable=True, comment='Nom du lieu-dit'),
    sa.Column('ad_x_ban', sa.Numeric(), nullable=True, comment='X en lambert 93'),
    sa.Column('ad_y_ban', sa.Numeric(), nullable=True, comment='Y en lambert 93'),
    sa.Column('ad_section', sa.String(length=5), nullable=True, comment='Section cadastrale'),
    sa.Column('ad_idpar', sa.String(length=20), nullable=True, comment='Identifiant de la parcelle de référence'),
    sa.Column('ad_x_parc', sa.Numeric(), nullable=True, comment='X en lambert 93 de la parcelle de référence'),
    sa.Column('ad_y_parc', sa.Numeric(), nullable=True, comment='Y en lambert 93 de la parcelle de référence'),
    sa.Column('ad_nat', sa.String(length=1), nullable=True, comment="Oui si le site n'est pas une propriété privée"),
    sa.Column('ad_rivoli', sa.String(length=254), nullable=True, comment='Code RIVOLI'),
    sa.Column('ad_hexaclv', sa.String(length=254), nullable=True, comment='Code HEXACLE Voie'),
    sa.Column('ad_itypeim', sa.String(length=1), nullable=True, comment="Type d'immeuble (IPE)"),
    sa.Column('ad_idatimn', sa.DateTime(), nullable=True, comment="Date prévisionnelle de livraison de l'immeuble"),
    sa.Column('ad_prop', sa.String(length=254), nullable=True, comment="Propriétaire de l'immeuble"),
    sa.Column('ad_idatcab', sa.DateTime(), nullable=True, comment="Date prévisionnelle de câblage de l'adresse"),
    sa.Column('ad_idatcom', sa.Date(), nullable=True, comment="Date d'ouverture à la commercialisation"),
    sa.Column('ad_typzone', sa.String(length=1), nullable=True, comment="Type de zone de l'adresse desservie"),
    sa.Column('ad_comment', sa.String(length=254), nullable=True, comment='Commentaire'),
    sa.Column('ad_geolqlt', sa.NUMERIC(precision=6, scale=2), nullable=True, comment='Précision du positionnement en mètres'),
    sa.Column('ad_geolmod', sa.String(length=4), nullable=True, comment="Mode d'implantation de l'objet"),
    sa.Column('ad_geolsrc', sa.String(length=254), nullable=True, comment='Source de la géolocalisation'),
    sa.Column('ad_creadat', sa.DateTime(), nullable=True, comment="Date de création de l'objet en base"),
    sa.Column('ad_majdate', sa.DateTime(), nullable=True, comment="Date de mise à jour de l'objet en base"),
    sa.Column('ad_majsrc', sa.String(length=254), nullable=True, comment='Source utilisée pour la mise à jour'),
    sa.Column('ad_abddate', sa.DateTime(), nullable=True, comment="Date d'abandon de l'objet"),
    sa.Column('ad_abdsrc', sa.String(length=254), nullable=True, comment="Cause de l'abandon de l'objet"),
    sa.Column('ad_sracdem', sa.String(length=1), nullable=True, comment="Adresse susceptible d'être raccordable sur demande"),
    sa.PrimaryKeyConstraint('ad_code'),
    sa.UniqueConstraint('ad_batcode'),
    sa.UniqueConstraint('ad_codtemp'),
    schema='gracethd_commun'
    )
    with op.batch_alter_table('t_adresse', schema='gracethd_commun') as batch_op:
        batch_op.create_index('idx_t_adresse_geom', ['geom'], unique=False, postgresql_using='gist')

    op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    with op.batch_alter_table('t_adresse', schema='gracethd_commun') as batch_op:
        batch_op.drop_index('idx_t_adresse_geom', postgresql_using='gist')

    op.drop_table('t_adresse', schema='gracethd_commun')
    # ### end Alembic commands ###
